name:                mathfp
version:             0.1.0.0
github:              "popelde/mathfp"
license:             BSD3
author:              "popelde"
maintainer:          "50044800+popelde@users.noreply.github.com"
copyright:           "2020 popelde"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Teaching

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/popelde/mathfp#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  mathfp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mathfp

tests:
  mathfp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mathfp
